=== alxRbnk/sweetsXML/files/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies"
        xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">

    <element name="candies">
        <complexType>
            <sequence>
                <element name="candy" type="tns:Candy" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Candy">
        <sequence>
            <element name="energy" type="tns:Energy"/>
            <element name="date" type="date"/>
            <element name="production" type="string"/>
            <element name="value" type="tns:Value"/>
            <element name="ingredients" type="tns:Ingredients" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
        <attribute name="brand" type="tns:Brand" use="required"/>
        <attribute name="type" type="tns:Type" use="optional" default="chocolate"/>
    </complexType>

    <simpleType name="Brand">
        <restriction base="ID">
            <pattern value="[a-zA-Z0-9]+"/>
        </restriction>
    </simpleType>

    <simpleType name="Type">
        <restriction base="string">
            <enumeration value="chocolate"/>
            <enumeration value="chewy and fruit"/>
            <enumeration value="caramel and lollipops"/>
            <enumeration value="energy"/>
            <enumeration value="holiday"/>
        </restriction>
    </simpleType>

    <complexType name="Value">
        <sequence>
            <element name="protein" type="tns:Gram"/>
            <element name="carbohydrates" type="tns:Gram"/>
            <element name="fats" type="tns:Gram"/>
        </sequence>
    </complexType>

    <complexType name="Gram">
        <attribute name="gram" type="positiveInteger"/>
    </complexType>

    <complexType name="Ingredients">
        <sequence>
            <element name="water" type="tns:percent" />
            <element name="sugar" type="tns:percent"/>
            <element name="fructose" type="tns:percent"/>
            <element name="vanilla" type="tns:percent"/>
        </sequence>
    </complexType>

    <complexType name="percent">
        <attribute name="percent" type="positiveInteger"/>
    </complexType>

    <complexType name="Energy">
        <attribute name="calories" type="positiveInteger"/>
    </complexType>

</schema>

=== alxRbnk/sweetsXML/files/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/candies"
          xsi:schemaLocation="http://www.example.com/candies candies.xsd">

    <candy brand="Toffifee" type="toffee">
        <name>Toffifee</name>
        <energy>500</energy>
        <date>2023-11-19</date>
        <production>August Storck</production>
        <ingredients>water sugar fructose vanilla</ingredients>

        <!--water sugar fructose vanilla-->

        <value>
            <protein>5</protein>
            <carbohydrates>60</carbohydrates>
            <fats>20</fats>
        </value>

    </candy>




</candies>
